# -*- coding: utf-8 -*-
"""automate_Lilis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hrcEWNsqPFFtSmMS0atmRjpTOyOOulwj

# **1. Automate**
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
import os

def preprocess_diabetes_data(input_path, output_dir):
    """
    Fungsi otomatisasi untuk memuat, membersihkan, dan
    menyimpan dataset Pima Indians Diabetes langsung ke folder tujuan.
    """
    column_names = [
        'Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness',
        'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'
    ]

    # 1. Memuat Data Mentah
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"File mentah tidak ditemukan di: {input_path}")

    df = pd.read_csv(input_path, names=column_names, skiprows=1)

    # 2. Menangani Nilai Invalid 0 -> NaN
    invalid_zero_features = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
    df[invalid_zero_features] = df[invalid_zero_features].replace(0, np.nan)

    # 3. Imputasi dengan Median
    imputer = SimpleImputer(strategy='median')
    df[invalid_zero_features] = imputer.fit_transform(df[invalid_zero_features])

    # 4. Hapus Duplikat
    df = df.drop_duplicates()

    # 5. Memisahkan Fitur dan Target
    X = df.drop(columns=['Outcome'])
    y = df['Outcome']

    # 6. Standarisasi Fitur
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # 7. Menggabungkan Kembali ke DataFrame Bersih
    df_clean = pd.DataFrame(X_scaled, columns=X.columns)
    df_clean['Outcome'] = y.values

    # 8. Memastikan Direktori Tujuan Preprocessing Sudah Tersedia
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        print(f"Membuat folder baru: {output_dir}")

    # 9. Menyimpan ke Folder Preprocessing
    output_file_path = os.path.join(output_dir, "diabetes_clean.csv")
    df_clean.to_csv(output_file_path, index=False)
    print(f"Otomatisasi Berhasil! Data bersih disimpan di: {output_file_path}")

# Blok eksekusi utama jika file .py dijalankan langsung
if __name__ == "__main__":
    # Menyesuaikan dengan rekomendasi struktur folder Dicoding
    raw_data_path = "diabetes.csv"
    preprocessing_dir = "diabetes_preprocessing"

    preprocess_diabetes_data(raw_data_path, preprocessing_dir)